### ISSUE TITLE
Breaking changes in v2.0.0

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/java-algorand-sdk#389]
Itemizes functionality that will be removed in the upcoming major release.

Task list for algorand-sdk-testing stories:
- [x] https://github.com/algorand/algorand-sdk-testing/issues/201 - https://github.com/algorand/java-algorand-sdk/pull/445
- [x] https://github.com/algorand/algorand-sdk-testing/issues/202 - https://github.com/algorand/java-algorand-sdk/pull/441
- [x] https://github.com/algorand/algorand-sdk-testing/issues/223 - https://github.com/algorand/java-algorand-sdk/pull/442
- [x] https://github.com/algorand/algorand-sdk-testing/issues/254 - https://github.com/algorand/java-algorand-sdk/pull/442
- [x] https://github.com/algorand/algorand-sdk-testing/issues/255 - https://github.com/algorand/java-algorand-sdk/pull/443
- [x] Remove the deprecated `MethodCallParams` public constructor.  Deprecation added in https://github.com/algorand/java-algorand-sdk/pull/408. - https://github.com/algorand/java-algorand-sdk/pull/443
- [x] https://github.com/algorand/generator/issues/46 - https://github.com/algorand/generator/pull/50
